import {useEffect,useState} from 'react'
import {Panel,Field} from '../../components/Foundation'
import {ErrorFields,useOperation,type Json,type PageProps} from '../shared'
export default function Records({client,language,observation}:PageProps){
 const [tasks,setTasks]=useState<Json[]>([]),[selected,setSelected]=useState(()=>localStorage.getItem('agro.last_task')||''),[report,setReport]=useState<Json|null>(null),[logs,setLogs]=useState<Json|null>(null),[offset,setOffset]=useState(0)
 const op=useOperation(language)
 useEffect(()=>{let active=true;const controller=new AbortController();client.request<Json>('/tasks','GET',undefined,controller.signal).then(t=>{if(active)setTasks(t.tasks)}).catch(e=>{if(active)op.setError(e)});return()=>{active=false;controller.abort()}},[client,observation])
 async function read(){const [r,l]=await Promise.all([client.request<Json>(`/tasks/${selected}/report`),client.request<Json>(`/tasks/${selected}/logs?offset=${offset}&limit=16384`)]);setReport(r);setLogs(l)}
 const text=JSON.stringify(report,null,2)
 return <><Panel title="任务记录与故障报告" subtitle="查看任务结果、设备状态及故障信息" icon="runtime"><Field label="任务运行 ID"><select value={selected} onChange={e=>{setSelected(e.target.value);setReport(null);setLogs(null);setOffset(0)}}><option value="">选择已有任务</option>{tasks.map(t=><option key={t.task_run_id} value={t.task_run_id}>{t.task_run_id} · {t.state}</option>)}</select></Field><div className="buttons"><button disabled={op.busy||!selected} onClick={()=>void op.run('读取冻结记录与日志',read)}>读取记录</button><button disabled={!report} onClick={()=>void op.run('复制脱敏报告',async()=>{if(window.agroDesktop)await window.agroDesktop.copyReport(selected);else await navigator.clipboard.writeText(text)})}>复制报告</button><button disabled={!report} onClick={()=>{if(window.agroDesktop){void op.run('导出脱敏报告',async()=>{await window.agroDesktop!.exportReport(selected)});return}const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=selected+'.report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>导出 JSON 报告</button></div>{report&&<><p>任务快照 {report.task.snapshot_id}</p><p>系统快照 {report.task.system_snapshot_id}</p><p>状态 {report.task.state} · 停止{report.task.stop_confirmed?'已确认':'未确认'}</p><pre className="selectable">{text}</pre></>}</Panel><Panel title="执行器日志" subtitle="查看执行器日志"><Field label="字节偏移"><input type="number" min={0} value={offset} onChange={e=>setOffset(Number(e.target.value))}/></Field><button disabled={!selected||op.busy} onClick={()=>void op.run('读取日志片段',read)}>读取日志</button>{logs&&<><pre className="selectable">{logs.text}</pre><button disabled={logs.eof} onClick={()=>setOffset(logs.next_offset)}>下一段</button></>}</Panel><ErrorFields value={op.error}/>{op.dialog()}</>
}
