import {editorText} from './messages'
import {useEffect,useRef,useState} from 'react'
import {Field,Panel} from '../../components/Foundation'
import {ApiError} from '../../api'
import {ErrorFields,Parameters,durableIntent,waitJob,useOperation,type Json,type PageProps} from '../shared'
import {clone,duplicate,nodeId,positions,remove,reparent,type EditorValue} from './editor'
import TreeCanvas from './TreeCanvas'
import RuntimeTree from './RuntimeTree'

export default function TaskEditor({client,observation,language,changed}:PageProps){
 const t=editorText(language)
 const [definitions,setDefinitions]=useState<Json[]>([]),[models,setModels]=useState<Json|null>(null),[drafts,setDrafts]=useState<Json[]>([]),[draft,setDraft]=useState<Json|null>(null),[value,setValue]=useState<EditorValue|null>(null),[treeId,setTreeId]=useState(''),[selected,setSelected]=useState(''),[registration,setRegistration]=useState('Capability_perception_detect_targets'),[diagnostics,setDiagnostics]=useState<Json[]>([]),[sources,setSources]=useState<Json[]>([]),[xml,setXml]=useState(''),[definition,setDefinition]=useState<Json|null>(null),[task,setTask]=useState<Json|null>(null),[dirty,setDirty]=useState(false),[proposal,setProposal]=useState<Json|null>(null),[subtreeName,setSubtreeName]=useState('Extracted'),[advanced,setAdvanced]=useState(''),[view,setView]=useState<'edit'|'run'>('edit'),[tasks,setTasks]=useState<Json[]>([]),[taskId,setTaskId]=useState(()=>localStorage.getItem('agro.last_task')||''),[stale,setStale]=useState(false)
 const history=useRef<{past:EditorValue[];future:EditorValue[]}>({past:[],future:[]}),taskIntent=useRef<string|null>(localStorage.getItem('agro.tree_request')),dirtyRef=useRef(false),op=useOperation(language),reader=useRef(0)
 async function load(){const [m,d,p]=await Promise.all([client.request<Json>('/trees/models'),client.request<Json>('/trees/drafts'),client.request<Json>('/trees/definitions')]);setModels(m);setDrafts(d.drafts);setDefinitions(p.definitions)}
 useEffect(()=>{let active=true;load().catch(e=>{if(active)op.setError(e)});return()=>{active=false}},[client])
 useEffect(()=>{dirtyRef.current=dirty;const unload=(e:BeforeUnloadEvent)=>{if(dirtyRef.current){e.preventDefault();e.returnValue=''}};const navigate=(e:Event)=>{if(dirtyRef.current&&!window.confirm(t("树草稿尚未保存，是否离开并放弃修改")))e.preventDefault()};window.addEventListener('beforeunload',unload);window.addEventListener('agro:navigate',navigate);return()=>{window.removeEventListener('beforeunload',unload);window.removeEventListener('agro:navigate',navigate)}},[dirty])
 useEffect(()=>{if(!value||draft?.document.readonly)return;const controller=new AbortController();const timer=setTimeout(()=>{client.request<Json>('/trees/validate','POST',{document:value.document,policy:draft?.policy,parameters:value.parameters},controller.signal).then(result=>{if(!controller.signal.aborted){setDiagnostics(result.diagnostics);setSources(result.sources)}}).catch(e=>{if(!controller.signal.aborted)op.setError(e)})},450);return()=>{clearTimeout(timer);controller.abort()}},[value?.document,value?.parameters,client,draft?.policy])
 useEffect(()=>{let active=true;const controller=new AbortController(),sequence=++reader.current;async function read(){try{const response=await client.request<Json>('/tasks','GET',undefined,controller.signal);if(active)setTasks(response.tasks);if(taskId){const response=await client.request<Json>(`/tasks/${taskId}`,'GET',undefined,controller.signal);if(active&&sequence===reader.current)setTask(response)}else if(taskIntent.current){const found=await client.request<Json>(`/tasks/by-request/${taskIntent.current}`,'GET',undefined,controller.signal);if(active&&found.found)remember(found.task)}if(active)setStale(false)}catch(e){if(active){setStale(true);op.setError(e)}}}void read();return()=>{active=false;controller.abort()}},[client,observation,taskId])
 function choose(next:Json){setDraft(next);setValue({document:structuredClone(next.document),layout:structuredClone(next.layout),parameters:structuredClone(next.parameters)});setTreeId(next.document.main_tree_id);setSelected(next.document.trees[next.document.main_tree_id]?.root_id||'');setDirty(false);setDiagnostics(next.validation?.diagnostics||[]);setDefinition(definitions.find(d=>d.id===next.published)||null);setXml('');setProposal(null);history.current={past:[],future:[]}}
 function selectDraft(next:Json){if(dirty&&!window.confirm(t("树草稿尚未保存，是否切换并放弃修改")))return;choose(next)}
 function change(work:(next:EditorValue)=>void){if(!value||draft?.document.readonly)return;const next=clone(value);try{work(next);history.current.past.push(clone(value));history.current.past=history.current.past.slice(-50);history.current.future=[];setValue(next);setDirty(true);setProposal(null)}catch(e){op.setError(new ApiError('response',[{path:'$.tree',code:'edit_rejected',reason:e instanceof Error?e.message:t("编辑失败")}]))}}
 function undo(redo=false){if(!value)return;const from=redo?history.current.future:history.current.past,to=redo?history.current.past:history.current.future,next=from.pop();if(next){to.push(clone(value));const restored=next.document.trees[treeId]?treeId:next.document.main_tree_id;setTreeId(restored);setSelected(next.document.trees[restored].nodes[selected]?selected:next.document.trees[restored].root_id);setProposal(null);setValue(next);setDirty(true)}}
 const tree=value?.document.trees[treeId],node=tree?.nodes[selected],model=node&&models?.nodes[node.registration_id],readonly=!!draft?.document.readonly
 const specs:Json=node?.registration_id==='SubTree'?Object.fromEntries(Object.entries(value?.document.trees[node.attributes.ID]?.ports||{}).map(([key,v]:[string,any])=>[key,{...v.type,direction:v.direction,required:true}])):model?.ports||{}
 function setPort(name:string,next:Json|undefined){change(v=>{const ports=v.document.trees[treeId].nodes[selected].ports;if(next)ports[name]=next;else delete ports[name]})}
 async function save(){if(!draft||!value)return draft;const next=await client.request<Json>(`/trees/drafts/${draft.id}`,'PUT',{revision:draft.revision,layout_revision:draft.layout_revision,...value});setDraft(next);setValue({document:next.document,layout:next.layout,parameters:next.parameters});setDirty(false);await load();return next}
 async function checked(){const current=dirty?await save():draft;if(!current)return null;const result=await client.request<Json>(`/trees/drafts/${current.id}/validate`,'POST',{});setDiagnostics(result.diagnostics);setSources(result.sources);if(!result.valid)throw new ApiError('response',result.diagnostics.map((d:Json)=>({path:`${d.tree_id||'$'}/${d.editor_id||''}/${d.port||''}`,code:d.code,reason:d.reason})));return current}
 function add(){if(!tree||!models)return;change(v=>{const target=v.document.trees[treeId],id=nodeId(),ports:Json={},attributes:Json={};const spec=models.nodes[registration];if(spec.capability_id){attributes.role=spec.roles[0]||'';for(const [name,p] of Object.entries(spec.ports) as [string,Json][])if(p.direction==='OUTPUT')ports[name]={kind:'blackboard_reference',key:name.replace('out_','')+'_'+id.slice(-6),type:{},value:null}}if(registration==='SubTree')attributes.ID=Object.keys(v.document.trees).find(k=>k!==treeId)||'';target.nodes[id]={editor_id:id,registration_id:registration,children:[],ports,attributes};let parent=selected;if(models.nodes[target.nodes[parent]?.registration_id]?.maximum_children===0)parent=(Object.values(target.nodes) as Json[]).find(n=>n.children.includes(selected))?.editor_id||target.root_id;target.nodes[parent].children.push(id);setSelected(id)})}
 function order(delta:number){change(v=>{const target=v.document.trees[treeId],parent=(Object.values(target.nodes) as Json[]).find(n=>n.children.includes(selected));if(!parent)return;const index=parent.children.indexOf(selected),next=index+delta;if(next>=0&&next<parent.children.length)[parent.children[index],parent.children[next]]=[parent.children[next],parent.children[index]]})}
 function remember(next:Json){setTask(next);setTaskId(next.task_run_id);localStorage.setItem('agro.last_task',next.task_run_id)}
 async function stopSystem(phase:(v:string)=>void,signal:AbortSignal){const job=await client.request<Json>('/system/stop','POST',{});await waitJob(client,job.management_job_id,phase,signal);await changed()}
 async function cancelTask(phase:(v:string)=>void,signal:AbortSignal){if(!task)return;remember(await client.request<Json>(`/tasks/${task.task_run_id}/cancel`,'POST',{}));const deadline=Date.now()+15000;while(Date.now()<deadline){signal.throwIfAborted();const next=await client.request<Json>(`/tasks/${task.task_run_id}`,'GET',undefined,signal);remember(next);phase(`取消 ${next.state} · 停止${next.stop_confirmed?t("已确认"):t("未确认")}`);if(!['RUNNING','ACCEPTED','CANCELING'].includes(next.state)){if(!next.stop_confirmed)throw new ApiError('response',[{path:'$.stop_confirmed',code:'stop_unconfirmed',reason:t("节点已停止派发，设备停止未确认")}]);return}await new Promise(r=>setTimeout(r,400))}throw new ApiError('response',[{path:'$.task',code:'observation_timeout',reason:t("观察等待结束，请继续按原任务核对")}])}
 async function start(){if(!definition)return;const request=durableIntent('tree-start',{definition_id:definition.id,previous:task&&!['RUNNING','ACCEPTED','CANCELING'].includes(task.state)?task.task_run_id:null});taskIntent.current=request;localStorage.setItem('agro.tree_request',request);try{remember(await client.request<Json>(`/trees/definitions/${definition.id}/start`,'POST',{request_id:request}))}catch(e){if(e instanceof ApiError&&e.kind==='offline'){const found=await client.request<Json>(`/tasks/by-request/${request}`);if(found.found)remember(found.task);else throw e}else throw e}setView('run');await changed()}
 return <><div className="buttons"><button disabled={op.busy} onClick={()=>void op.run(t("新建模拟查询树"),async()=>{if(dirty&&!window.confirm(t("放弃未保存修改并新建")))return;choose(await client.request<Json>('/trees/drafts','POST',{template:'simulation_inspection'}));await load()})}>{t("新建查询树")}</button><button disabled={op.busy} onClick={()=>void op.run(t("复制番茄模板"),async()=>{if(dirty&&!window.confirm(t("放弃未保存修改并新建")))return;choose(await client.request<Json>('/trees/drafts','POST',{template:'tomato_picker'}));await load()})}>{t("从番茄模板创建")}</button><label className="file-button">{t("导入 XML")}<input type="file" accept=".xml" aria-label={t("导入树 XML")} disabled={op.busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void op.run(t("解析 XML"),async()=>{if(file.size>1048576)throw Error(t("XML 过大"));if(dirty&&!window.confirm(t("放弃未保存修改并导入")))return;choose(await client.request<Json>('/trees/drafts','POST',{xml:await file.text(),template:draft?.policy||'simulation_inspection'}));await load()})}}/></label><button onClick={()=>setView(view==='edit'?'run':'edit')}>{view==='edit'?t("查看运行树"):t("回到编辑")}</button></div>
 <Field label={t("树草稿")}><select value={draft?.id||''} onChange={e=>{const next=drafts.find(d=>d.id===e.target.value);if(next)selectDraft(next)}}><option value="">{t("选择草稿")}</option>{drafts.map(d=><option key={d.id} value={d.id}>{d.document.main_tree_id} · {d.policy} · revision {d.revision} · {d.id.slice(-8)}</option>)}</select></Field>
 <Field label={t("已发布定义")}><select value={definition?.id||''} onChange={e=>setDefinition(definitions.find(d=>d.id===e.target.value)||null)}><option value="">{t("选择固定定义")}</option>{definitions.map(d=><option key={d.id} value={d.id}>{d.document.main_tree_id} · {d.id}</option>)}</select></Field>
 {draft&&<p className="muted">{dirty?t("编辑中 · 未保存"):t("已保存")} · revision {draft.revision} · {draft.policy} · {t('已发布')} {draft.published||t("尚未发布")}</p>}
 {view==='run'?<><Field label={t("观察原任务")}><select value={taskId} onChange={e=>{setTaskId(e.target.value);setTask(null);localStorage.setItem('agro.last_task',e.target.value)}}><option value="">{t("选择任务")}</option>{tasks.map(t=><option key={t.task_run_id} value={t.task_run_id}>{t.task_run_id} · {t.state}</option>)}</select></Field>{stale&&<p className="error">{t("数据陈旧 · 保留原任务 ID，恢复后只查询原快照")}</p>}{task&&<><p>{task.task_run_id} · {task.state} · {t('停止')}{task.stop_confirmed?t("已确认"):t("未确认")}</p><div className="buttons"><button disabled={op.busy||!['RUNNING','ACCEPTED','CANCELING'].includes(task.state)} onClick={()=>void op.run(t("请求取消并保留停止观察"),cancelTask)}>{t("取消运行任务")}</button><button onClick={()=>void op.run(t("请求停止系统"),stopSystem)}>{t("停止系统")}</button></div><RuntimeTree task={task} language={language}/></>}</>:tree&&value&&<>
 {readonly&&<p className="error">{t('未支持的 XML 已保留为只读')} · {value.document.unsupported.join('、')} · {t('不允许覆盖或发布')}</p>}
 <div className="buttons"><button disabled={op.busy||readonly} onClick={()=>void op.run(t("保存树与布局"),async()=>{await save()})}>{t("保存草稿")}</button><button disabled={!history.current.past.length||readonly} onClick={()=>undo()}>{t("撤销")}</button><button disabled={!history.current.future.length||readonly} onClick={()=>undo(true)}>{t("重做")}</button><button disabled={op.busy||readonly} onClick={()=>void op.run(t("结构、数据与实际引擎校验"),async()=>{await checked()})}>{t("校验树")}</button><button disabled={op.busy||readonly} onClick={()=>void op.run(t("冻结并发布任务定义"),async()=>{const current=await checked();if(current){setDefinition(await client.request<Json>(`/trees/drafts/${current.id}/publish`,'POST',{revision:current.revision,base_snapshot_id:observation?.system.snapshot_id}));await load()}})}>{t("发布定义")}</button><button disabled={op.busy||readonly} onClick={()=>void op.run(t("导出已保存 XML"),async()=>{const current=dirty?await save():draft;if(!current)return;const result=await client.request<Json>(`/trees/drafts/${current.id}/xml`);setXml(result.xml);if(window.agroDesktop)await window.agroDesktop.exportTreeXml(current.id)})}>{t("导出 XML")}</button><button onClick={()=>void op.run(t("重新加载草稿"),async()=>{if(dirty&&!window.confirm(t("重新加载会放弃未保存修改")))return;choose(await client.request<Json>(`/trees/drafts/${draft!.id}`));await load()})}>{t("重新加载")}</button></div>
 <div className="parameter-grid"><Field label={t("编辑树定义")}><select value={treeId} onChange={e=>{setTreeId(e.target.value);setSelected(value.document.trees[e.target.value].root_id)}}>{Object.keys(value.document.trees).map(id=><option key={id}>{id}</option>)}</select></Field><Field label={t("执行根树")}><select disabled={readonly} value={value.document.main_tree_id} onChange={e=>change(v=>{v.document.main_tree_id=e.target.value})}>{Object.keys(value.document.trees).map(id=><option key={id}>{id}</option>)}</select></Field></div>
 <div className="tree-editor-grid">
 <Panel title={t("实际节点库")} subtitle={t("来自 C++ 注册与当前系统契约")}><Field label={t("添加节点类型")}><select value={registration} onChange={e=>setRegistration(e.target.value)}>{Object.values(models?.nodes||{}).filter((m:any)=>m.editable).map((m:any)=><option key={m.registration_id} value={m.registration_id}>{m.registration_id} · {m.category}</option>)}</select></Field><p className="muted">{models?.nodes[registration]?.description||models?.nodes[registration]?.category}</p><button disabled={readonly||op.busy} onClick={add}>{t("添加节点")}</button><p className="muted">{t("能力角色来自当前系统，未绑定能力不会提供可执行节点")}</p><details><summary>{t("模型摘要")}</summary><code>{models?.digest}</code></details></Panel>
 <Panel title={t("控制树画布")} subtitle={t("拖动只修改布局，执行顺序由子节点序号决定")}><div className="buttons"><button onClick={()=>change(v=>{v.layout.positions={...v.layout.positions,...positions(tree)}})}>{t("自动布局")}</button><button onClick={()=>change(v=>{v.layout.zoom=Math.max(.2,Math.min(1,650/(Object.keys(tree.nodes).length*130)));v.layout.positions={...v.layout.positions,...positions(tree)}})}>{t("适配视图")}</button><button onClick={()=>change(v=>{v.layout.zoom=Math.max(.2,v.layout.zoom-.1)})}>{t("缩小")}</button><button onClick={()=>change(v=>{v.layout.zoom=Math.min(3,v.layout.zoom+.1)})}>{t("放大")}</button><span>{Math.round(value.layout.zoom*100)}%</span></div><div onKeyDown={e=>{if(e.altKey&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();order(e.key==='ArrowUp'?-1:1)}}}><TreeCanvas language={language} tree={tree} layout={value.layout} selected={selected} onSelect={setSelected} onMove={readonly?undefined:(id,x,y)=>change(v=>{v.layout.positions[id]=[x,y]})} bindings={sources.filter(s=>s.editor_id===selected)} portModels={Object.fromEntries((Object.values(tree.nodes) as Json[]).map(n=>[n.editor_id,n.registration_id==='SubTree'?value.document.trees[n.attributes.ID]?.ports||{}:models?.nodes[n.registration_id]?.ports||{}]))}/></div></Panel>
 <Panel title={t("属性与数据绑定")} subtitle={t("显示名不参与执行或采摘阶段证明")}>
 {node&&<><code>{node.editor_id}</code><Field label={t("节点显示名")}><input disabled={readonly} value={value.layout.labels[selected]||''} onChange={e=>change(v=>{v.layout.labels[selected]=e.target.value})}/></Field><p>{node.registration_id} · {t('子节点')} {node.children.length} · {t('要求')} {model?.minimum_children} 至 {model?.maximum_children===-1?t("不限"):model?.maximum_children}</p>
 <Field label={t("控制父节点")}><select disabled={readonly||selected===tree.root_id} value={(Object.values(tree.nodes) as Json[]).find(n=>n.children.includes(selected))?.editor_id||''} onChange={e=>change(v=>reparent(v.document.trees[treeId],selected,e.target.value))}><option value="">{t("根节点")}</option>{(Object.values(tree.nodes) as Json[]).filter(n=>models?.nodes[n.registration_id]?.maximum_children!==0).map(n=><option key={n.editor_id} value={n.editor_id}>{value.layout.labels[n.editor_id]||n.registration_id} · {n.editor_id.slice(-6)}</option>)}</select></Field>
 <div className="buttons"><button disabled={readonly} onClick={()=>order(-1)}>{t("上移")}</button><button disabled={readonly} onClick={()=>order(1)}>{t("下移")}</button><button disabled={readonly||selected===tree.root_id} onClick={()=>change(v=>{setSelected(duplicate(v.document.trees[treeId],selected,Object.fromEntries((Object.values(tree.nodes) as Json[]).map(n=>[n.editor_id,n.registration_id==='SubTree'?value.document.trees[n.attributes.ID]?.ports||{}:models?.nodes[n.registration_id]?.ports||{}]))))})}>{t("复制节点片段")}</button><button disabled={readonly||selected===tree.root_id} onClick={()=>change(v=>{remove(v.document.trees[treeId],selected);setSelected(tree.root_id)})}>{t("删除节点片段")}</button><button onClick={()=>change(v=>{v.layout.collapsed=v.layout.collapsed.includes(selected)?v.layout.collapsed.filter((id:string)=>id!==selected):[...v.layout.collapsed,selected]})}>{value.layout.collapsed.includes(selected)?t("展开"):t("折叠")}</button></div>
 {model?.capability_id&&<Field label={t("绑定能力角色")}><select disabled={readonly} value={node.attributes.role||'backend:'+node.attributes.backend_instance} onChange={e=>change(v=>{const attrs=v.document.trees[treeId].nodes[selected].attributes;delete attrs.role;delete attrs.backend_instance;if(e.target.value.startsWith('backend:'))attrs.backend_instance=e.target.value.slice(8);else attrs.role=e.target.value})}><option value="">{t("选择兼容绑定")}</option>{model.roles.map((role:string)=><option key={role}>{role}</option>)}{model.backends.map((backend:string)=><option key={backend} value={'backend:'+backend}>{t('实例')} {backend}</option>)}</select></Field>}
 {node.registration_id==='SubTree'&&<Field label={t("被调用子树")}><select value={node.attributes.ID} onChange={e=>change(v=>{v.document.trees[treeId].nodes[selected].attributes.ID=e.target.value;v.document.trees[treeId].nodes[selected].ports={}})}><option value="">{t("选择子树")}</option>{Object.keys(value.document.trees).filter(k=>k!==treeId).map(k=><option key={k}>{k}</option>)}</select></Field>}
 {Object.entries(specs).filter(([name])=>!['role','backend_instance','node_id'].includes(name)).map(([name,spec]:[string,any])=>{const port=node.ports[name],output=spec.direction==='OUTPUT';return <div className="tree-port" key={name}><strong>{name} · {spec.direction}</strong><p className="muted">{spec.type} {spec.unit} {spec.frame_id} {spec.clock_domain} {spec.max_age_s?`${t('有效期')} ${spec.max_age_s} s`:''}</p><Field label={`${name} ${t('绑定方式')}`}><select disabled={readonly} value={port?.kind||''} onChange={e=>setPort(name,e.target.value?{kind:e.target.value,key:e.target.value==='blackboard_reference'?name.replace('out_','')+'_'+selected.slice(-6):null,value:e.target.value==='typed_literal'?(spec.type==='boolean'?false:spec.type==='string'?'':null):null,type:e.target.value==='typed_literal'?{type:spec.type,...(spec.unit?{unit:spec.unit}:{})}:{}}:undefined)}><option value="">{t("使用缺省或未绑定")}</option>{!output&&<option value="typed_literal">{t("常量")}</option>}<option value="blackboard_reference">{t("Blackboard / 任务输入")}</option></select></Field>{port?.kind==='blackboard_reference'?<Field label={`${name} ${t('变量')}`}><input disabled={readonly} value={port.key||''} onChange={e=>setPort(name,{...port,key:e.target.value})} list="tree-variables"/></Field>:port?.kind==='typed_literal'&&<>{spec.type==='boolean'?<Field label={`${name} ${t('常量')}`}><select value={String(port.value)} onChange={e=>setPort(name,{...port,value:e.target.value==='true'})}><option value="true">true</option><option value="false">false</option></select></Field>:<Field label={`${name} ${t('常量')}`}><input disabled={readonly} type={['integer','number'].includes(spec.type)?'number':'text'} step={spec.type==='integer'?1:'any'} min={spec.minimum} max={spec.maximum} value={typeof port.value==='object'?JSON.stringify(port.value):port.value??''} onChange={e=>{let next:unknown=e.target.value;if(['integer','number'].includes(spec.type))next=e.target.value===''?null:Number(e.target.value);else if(!['string'].includes(spec.type)){try{next=JSON.parse(e.target.value)}catch{next=e.target.value}}setPort(name,{...port,value:next})}}/></Field>}{spec.unit&&<Field label={`${name} ${t('单位')}`}><input disabled={readonly} value={port.type.unit||''} onChange={e=>setPort(name,{...port,type:{...port.type,unit:e.target.value}})}/></Field>}</>}{spec.choices&&<small>{t('可选值')} {JSON.stringify(spec.choices)}</small>}</div>})}
 <datalist id="tree-variables">{Array.from(new Set([...Object.keys(value.document.inputs||{}),...sources.map(s=>s.key)])).map(k=><option key={k}>{k}</option>)}</datalist>
 <h3>{t("提取子树")}</h3><Field label={t("新子树标识")}><input value={subtreeName} onChange={e=>setSubtreeName(e.target.value)}/></Field><button disabled={readonly||op.busy} onClick={()=>void op.run(t("分析跨边界端口"),async()=>setProposal(await client.request<Json>('/trees/extract','POST',{document:value.document,tree_id:treeId,editor_id:selected,subtree_id:subtreeName})))}>{t("预览子树端口")}</button>
 {proposal&&<><pre>{JSON.stringify(proposal.proposal,null,2)}</pre><button onClick={()=>void op.run(t("确认显式端口并提取"),async()=>{const result=await client.request<Json>('/trees/extract','POST',{document:value.document,tree_id:treeId,editor_id:selected,subtree_id:subtreeName,ports:proposal.proposal});change(v=>{v.document=result.document});setSelected(result.call_id);setProposal(null)})}>{t("确认端口并提取子树")}</button></>}
 </>}
 </Panel></div>
 <Panel title={t("任务输入与子树端口")} subtitle={t("显式作用域，缺省参数不被空白值覆盖")}><Parameters specs={draft?.policy==='tomato_picker'?{approach_dz:{type:'number',unit:'m',minimum:.01,maximum:.1,default:.05,apply_policy:'idle'}}:value.document.inputs||{}} value={value.parameters} onChange={parameters=>change(v=>{v.parameters=parameters})}/><details><summary>{t("声明任务输入或当前子树端口 JSON")}</summary><Field label={t("输入与端口声明 JSON")}><textarea value={advanced} placeholder={JSON.stringify({inputs:value.document.inputs||{},ports:tree.ports},null,2)} onChange={e=>setAdvanced(e.target.value)}/></Field><button onClick={()=>{try{const next=JSON.parse(advanced);change(v=>{v.document.inputs=next.inputs||{};v.document.trees[treeId].ports=next.ports||{}})}catch{op.setError(new ApiError('response',[{path:'$.ports',code:'invalid_json',reason:t("端口声明不是合法 JSON")}]))}}}>{t("应用声明")}</button></details><p className="muted">{t('当前作用域')} {treeId} · {t('任务输入')} {Object.keys(value.document.inputs||{}).join('、')||t("模板内置或无输入")}</p></Panel>

 {(xml||readonly)&&<Panel title={t("标准 XML")}><pre>{readonly?value.document.original_xml:xml}</pre></Panel>}
 </>}
 {definition&&<Panel title={t("不可变发布定义")}><p>{definition.id}</p><p>{t('XML 摘要')} {definition.xml_sha256} · {t('系统')} {definition.system_snapshot_id}</p><button className="primary" disabled={op.busy||observation?.system.state!=='READY'||observation?.control.mode!=='STANDBY'} onClick={()=>void op.run(t("开始发布任务并核对原请求"),start)}>{t("开始发布任务")}</button><p className="muted">{dirty?t("当前修改尚未发布，启动仍使用此固定定义 · "):''}{t('先在运行调试启动系统，发布不会自动启动模块或任务')}</p></Panel>}
 <Panel title={t("校验诊断与变量来源")}><div className="tree-diagnostics" role="status">{diagnostics.length?diagnostics.map((d,i)=><button key={i} className="diagnostic error" onClick={()=>{if(d.tree_id&&value?.document.trees[d.tree_id])setTreeId(d.tree_id);if(d.editor_id)setSelected(d.editor_id)}}>{d.tree_id} / {d.editor_id?.slice(-8)} / {d.port} · {d.reason} ({d.code})</button>):<p>{t("尚无错误或尚未完成实际引擎校验，发布时再次校验")}</p>}</div><details><summary>{t("当前输入来源与类型")}</summary><pre>{JSON.stringify(sources,null,2)}</pre></details></Panel>
 <ErrorFields value={op.error}/>{op.dialog(<><button disabled={!task||!['RUNNING','ACCEPTED','CANCELING'].includes(task.state)} onClick={()=>{if(task)void client.request(`/tasks/${task.task_run_id}/cancel`,'POST',{}).then(()=>changed()).catch(op.setError)}}>{t("取消当前任务")}</button><button onClick={()=>void client.request('/system/stop','POST',{}).then(()=>changed()).catch(op.setError)}>{t("请求停止系统")}</button></>)}</>
}
