import {editorText} from './messages'
import {useEffect,useRef,useState} from 'react'
import type {Json} from '../shared'
import {positions} from './editor'
import {nodeLabel} from './labels'
export default function TreeCanvas({tree,layout,selected,onSelect,onMove,onInsert,states={},lastStates={},bindings=[],portModels={},language='zh',fit=false}:{tree:Json;layout:Json;selected:string;onSelect(id:string):void;onMove?(id:string,x:number,y:number):void;onInsert?:(parentId:string,registration:string)=>void;states?:Record<string,string>;lastStates?:Record<string,string>;bindings?:Json[];portModels?:Json;language?:'zh'|'en';fit?:boolean}){
 const t=editorText(language)
 const viewport=useRef<HTMLDivElement>(null),[available,setAvailable]=useState(800)
 useEffect(()=>{const observer=new ResizeObserver(entries=>setAvailable(entries[0]?.contentRect.width||800));if(viewport.current)observer.observe(viewport.current);return()=>observer.disconnect()},[])
 const svg=useRef<SVGSVGElement>(null),drag=useRef<{id:string;x:number;y:number;px:number;py:number}|null>(null),[preview,setPreview]=useState<Record<string,[number,number]>>({})
 const automatic=positions(tree,layout.collapsed),locations={...automatic,...layout.positions,...preview} as Record<string,[number,number]>,visible=new Set<string>()
 function visit(id:string){if(visible.has(id)||!tree.nodes[id])return;visible.add(id);if(!layout.collapsed.includes(id))tree.nodes[id].children.forEach(visit)}visit(tree.root_id)
 for(const id of Object.keys(tree.nodes))if(!automatic[id])visible.add(id)
 const width=Math.max(800,...[...visible].map(id=>locations[id][0]+225)),height=Math.max(400,...[...visible].map(id=>locations[id][1]+105)),zoom=fit?Math.max(.1,Math.min(1,(available-20)/width)):layout.zoom||1
 return <div ref={viewport} className="tree-canvas" tabIndex={0} aria-label={t("行为树画布")} onDragOver={e=>{if(onInsert&&e.dataTransfer.types.includes('application/x-agro-node')){e.preventDefault();e.dataTransfer.dropEffect='copy'}}} onDrop={e=>{if(!onInsert)return;const registration=e.dataTransfer.getData('application/x-agro-node');if(!registration)return;e.preventDefault();const element=e.target instanceof Element?e.target.closest('[data-editor-id]'):null;onInsert(element?.getAttribute('data-editor-id')||selected,registration)}}><svg ref={svg} style={{width:width*zoom,height:height*zoom,display:'block',stroke:'none'}} width={width*zoom} height={height*zoom} viewBox={`0 0 ${width} ${height}`} onPointerMove={e=>{const value=drag.current;if(value)setPreview({[value.id]:[Math.max(0,value.x+(e.clientX-value.px)/zoom),Math.max(0,value.y+(e.clientY-value.py)/zoom)]})}} onPointerUp={()=>{const value=drag.current;if(value){const next=preview[value.id];if(next)onMove?.(value.id,next[0],next[1]);drag.current=null;setPreview({})}}} onPointerCancel={()=>{drag.current=null;setPreview({})}}>
 {[...visible].flatMap(id=>tree.nodes[id].children.filter((c:string)=>visible.has(c)).map((child:string,index:number)=>{const a=locations[id],b=locations[child];return <g key={id+child}><path className="tree-control-edge" d={`M ${a[0]+95} ${a[1]+70} V ${a[1]+92} H ${b[0]+95} V ${b[1]}`}/><text className="tree-order" x={b[0]+100} y={b[1]-5}>{index+1}</text></g>}))}
 {bindings.flatMap((binding,index)=>(binding.producers||[]).filter((p:Json)=>p.tree_id===tree.tree_id&&p.kind==='node_output'&&tree.nodes[p.editor_id]&&portModels[p.editor_id]?.[p.port]?.direction==='OUTPUT').map((producer:Json)=>{if(!locations[producer.editor_id]||!locations[selected])return null;const a=locations[producer.editor_id],b=locations[selected];return <path key={index+producer.editor_id+producer.port} className="tree-data-edge" d={`M ${a[0]+190} ${a[1]+35} Q ${(a[0]+b[0])/2+220} ${Math.min(a[1],b[1])-40} ${b[0]+190} ${b[1]+35}`}/>}))}
 {[...visible].map(id=>{const node=tree.nodes[id],p=locations[id];return <g key={id} transform={`translate(${p[0]} ${p[1]})`} className={`tree-node ${selected===id?'selected':''} state-${states[id]||'IDLE'}`} role="button" tabIndex={0} aria-label={`${t('节点')} ${layout.labels[id]||node.registration_id} ${id}`} data-editor-id={id} data-last-state={lastStates[id]} onClick={()=>onSelect(id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(id)}}} onPointerDown={e=>{if(!onMove||e.button!==0)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={id,x:p[0],y:p[1],px:e.clientX,py:e.clientY}}}><rect width={190} height={70} rx={10}/><text x={10} y={23}>{(layout.labels[id]||nodeLabel(node.registration_id,language)).slice(0,24)}</text><text className="tree-node-meta" x={10} y={43}>{node.attributes.role||node.attributes.ID||id.slice(-10)}</text><text className="tree-node-meta" x={10} y={59}>{states[id]||t("编辑节点")}{states[id]==='IDLE'&&lastStates[id]?` · ${t("上次")} ${lastStates[id]}`:''}{layout.collapsed.includes(id)?t(" · 已折叠"):''}</text></g>})}
 </svg></div>
}
