import { useEffect,useState } from 'react'
import { Panel,Field } from '../../components/Foundation'
import { Parameters,ErrorFields,useOperation,type Json,type PageProps } from '../shared'
export default function TaskSetup({client,language,onOpenEditor}:PageProps & {onOpenEditor:()=>void}){
 const [template,setTemplate]=useState<Json|null>(null),[assets,setAssets]=useState<Json[]>([]),[plans,setPlans]=useState<Json[]>([]),[parameters,setParameters]=useState<Json>({}),[assetId,setAssetId]=useState(''),[selected,setSelected]=useState(''),[check,setCheck]=useState<Json|null>(null)
 const op=useOperation(language)
 async function load(){const [t,a,p]=await Promise.all([client.request<Json>('/templates'),client.request<Json>('/assets'),client.request<Json>('/plans')]);setTemplate(t.templates[0]||null);setAssets(a.assets);setPlans(p.plans)}
 useEffect(()=>{void load().catch(op.setError)},[client])
 if(!template)return <Panel title="当前机器人尚未安装任务模板" icon="templates"><p>可从空白行为树创建任务，或导入包含模板的系统</p><button onClick={onOpenEditor}>打开行为树编辑器 →</button></Panel>
 return <><div className="workspace-grid"><Panel title="任务模板与参数" icon="templates"><h3>{template?.title}</h3><p className="callout">模拟任务 · 候选上限 {template?.manifest.max_targets} · 恢复次数 {template?.manifest.max_recovery_attempts}（只读）</p>
 <Parameters specs={template?.manifest.parameters||{}} value={parameters} onChange={setParameters}/><Field label="绑定标定资产"><select value={assetId} onChange={e=>setAssetId(e.target.value)}><option value="">内置模拟标定</option>{assets.map(a=><option key={a.id} value={a.id}>{a.filename} · {a.sha256.slice(0,12)}</option>)}</select></Field>
 <button disabled={op.busy||!template} className="primary" onClick={()=>void op.run('保存任务方案',async()=>{const next=await client.request<Json>('/plans','POST',{parameters,asset_id:assetId||null,template_id:template.id});setSelected(next.id);setCheck(null);await load()})}>保存为新任务方案</button>
 <Field label="任务方案"><select value={selected} onChange={e=>{setSelected(e.target.value);setCheck(null)}}><option value="">未选择</option>{plans.map(p=><option key={p.id} value={p.id}>{p.id}</option>)}</select></Field><button disabled={op.busy||!selected} onClick={()=>void op.run('检查任务方案',async()=>setCheck(await client.request<Json>(`/plans/${selected}/preflight`)))}>预检方案</button>
 {check&&<><p role="status">{check.valid?'检查通过':'预检未通过'}</p><ErrorFields value={check.valid?null:check}/><pre>{JSON.stringify(check,null,2)}</pre></>}
 </Panel><Panel title="标定资产" subtitle="标定文件管理" icon="plug"><label className="file-button">导入已有资产<input type="file" accept=".json" aria-label="导入标定资产" disabled={op.busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void op.run('校验资产来源与支持范围',async()=>{if(file.size>1048576)throw Error('文件过大');await client.request('/assets','POST',{filename:file.name,content:await file.text()});await load()})}}/></label><p className="muted">当前只支持模拟标定资产，真机标定尚未接入</p>{assets.map(a=><div className="package-row" key={a.id}><div><strong>{a.filename} · 模拟</strong><p>{a.support}</p><pre>{JSON.stringify(a.metadata,null,2)}</pre><code>{a.sha256}</code></div></div>)}</Panel></div>
 <Panel title="行为树结构预览" subtitle="模板结构预览"><details><summary>查看模板 XML</summary><pre>{template?.xml}</pre></details><p>{language==='en'?'Use the behavior tree editor to change nodes or subtrees':'需要调整节点或子树？打开行为树编辑器'}</p><button onClick={onOpenEditor}>{language==='en'?'Open Task Design':'打开行为树编辑器'}</button></Panel><ErrorFields value={op.error}/>{op.dialog()}</>
}
