import type { Workspace } from '../types'

export type CourseId = 'basic' | 'tomato'
export type GuideStep = {
  id: string
  workspace: Workspace
  target: string
  chapter: string
  title: string
  purpose: string
  action: string
  expected: string
  hint?: string
  /** 只有后台操作成功或页面实际切换后才发送完成事件 */
  event?: string
}
export type GuideSession = { course: CourseId; index: number; fromCreation: boolean }

const step = (
  id: string, workspace: Workspace, target: string, chapter: string,
  title: string, purpose: string, action: string, expected: string,
  hint?: string, event?: string,
): GuideStep => ({ id, workspace, target, chapter, title, purpose, action, expected, hint, event })

const projectStart = (course: CourseId): GuideStep[] => course === 'basic' ? [
  step('blank-choice', 'overview', 'create-blank', '创建系统', '选择空白机器人',
    '空白机器人是一个不带设备驱动和任务的独立工作区',
    '在左侧「新建系统」区域点击「空白机器人」',
    '空白机器人选项会高亮，下面可以填写新系统名称',
    '这一步只选择创建方式，还没有生成机器人系统', 'guide:source:blank'),
  step('blank-name', 'overview', 'create-robot-name', '创建系统', '给机器人命名',
    '系统名称用于在总览中识别不同的机器人，不是后端实例 ID',
    '在「机器人系统名称」输入一个容易辨认的名字，例如「我的第一台机器人」',
    '名称出现在输入框中，创建按钮变为可点击',
    '此处只是教学示例，不要求使用固定名称'),
  step('blank-create', 'overview', 'create-robot-submit', '创建系统', '创建并选择系统',
    '创建成功后会在工作区保存一个新的机器人系统',
    '点击「创建并选择」并等待操作完成，不要连续重复点击',
    '总览顶部会显示当前系统名称，「选择已有系统」列表中也能找到它',
    '如果创建失败，请查看总览中的错误提示，不要直接跳到下一步', 'robot:created:blank'),
] : [
  step('example-choice', 'overview', 'create-tomato', '创建示例', '选择番茄采摘示例',
    '番茄示例包含四个共享模拟状态的后端和一套采摘任务模板',
    '在「新建系统」中点击「从示例创建」',
    '创建方式会切换为番茄示例，并自动填入建议名称',
    '这是能力层模拟，不是带物理引擎的三维仿真', 'guide:source:tomato_picker'),
  step('example-name', 'overview', 'create-robot-name', '创建示例', '确认示例名称',
    '示例会复制成你自己的机器人系统，与其他系统相互独立',
    '检查系统名称，必要时改成「番茄采摘练习」之类的名称',
    '系统名称已填写，创建按钮可以点击',
    '可以同时建立多个番茄示例，不会直接覆盖旧系统'),
  step('example-create', 'overview', 'create-robot-submit', '创建示例', '创建示例机器人',
    '创建后系统才会拥有番茄示例的任务和模拟后端',
    '点击「创建并选择」，等待配置加载完成',
    '总览显示新系统，后续可从系统搭建查看四个模拟后端',
    '创建成功并不等于已经启动机器人模块', 'robot:created:tomato_picker'),
]

const basicSteps: GuideStep[] = [
  step('system-entry', 'overview', 'nav-system', '了解工作区', '进入系统搭建',
    '机器人系统由后端、能力和任务三部分组成，系统搭建负责前两部分',
    '点击左侧导航中的「系统搭建」',
    '主区域切换到当前机器人的系统搭建页面',
    '如果没有选择机器人，请先在总览创建或选择一个空白机器人', 'nav:system'),
  step('four-groups', 'system', 'system-groups', '认识系统', '认识四类功能系统',
    '视觉负责感知，导航负责移动，机械臂负责运动，电控负责末端和其他设备',
    '查看四个系统卡片上的名称、能力数量和当前状态',
    '空白系统显示待配置是正常的，不代表软件故障',
    '四类卡片表示能力分组，不代表必须连接四台电脑'),
  step('config-intro', 'system', 'system-start-config', '配置工作流程', '先建立可编辑配置',
    '运行中的配置不能随便改动，因此需要先建立配置草稿',
    '找到「保存系统配置」区域中的「开始配置」按钮',
    '这一步只认识入口，不会更改系统运行状态'),
  step('draft-create', 'system', 'system-create-draft', '配置工作流程', '创建配置草稿',
    '草稿用于尝试修改后端、参数和能力绑定，只有应用后才影响系统',
    '点击「开始配置」并等待创建完成',
    '下方出现机器人参数、后端实例和保存按钮',
    '创建草稿不启动设备，也不会让未配置的后端自动就绪', 'config:draft-created'),
  step('identifiers', 'system', 'system-config-identity', '认识后端', '系统标识和运行主机',
    '系统标识用于区分配置，运行主机表示后端实际在哪台设备执行',
    '查看「系统标识」和「运行主机」，初次学习无需修改它们',
    '能区分机器人系统名称、系统标识和后端实例标识',
    '当前阶段主要使用 localhost，远程主机将在后续阶段支持'),
  step('backend-list', 'system', 'system-backend-list', '认识后端', '认识后端实例',
    '后端实例是一个实际运行的服务或进程，例如一个相机识别服务',
    '查看「已配置后端」列表，空白系统没有实例也正常',
    '你知道一个功能系统可以由一个或多个后端实例提供能力',
    '添加真实设备前，必须有对应的接入包描述和运行实现'),
  step('package-catalog', 'system', 'system-catalog-advanced', '认识后端', '接入包从哪里来',
    '接入包描述后端有哪些能力、输入输出是什么、如何启动',
    '点击「高级：接入包管理与配置历史」展开目录，找到「导入 package.yaml」',
    '能看到可用接入包的列表或导入入口',
    '没有自己的接入包时可只阅读本步，不必伪造驱动或接口'),
  step('backend-fields', 'system', 'system-backend-editor', '配置后端', '认识实例标识和接入包',
    '实例标识是当前系统中一个后端的名字，接入包是它遵守的接口描述',
    '查看「新实例标识」和「接入包」两个输入项，有可用接入包时才选择',
    '你知道添加一个后端需要实例名和接入包两个条件',
    '例如 vision_1 是实例名称，并不代表程序已经连接上相机'),
  step('add-backend', 'system', 'system-add-backend', '配置后端', '将后端加入草稿',
    '添加实例只修改当前草稿，不会启动对应的运行进程',
    '已经有可用接入包时，填写实例名称并选择接入包，然后点击「添加后端实例」',
    '「已配置后端」区域会增加对应实例',
    '没有可用接入包时可点击「下一步」，先完成界面学习'),
  step('role-binding', 'system', 'system-advanced-roles', '配置后端', '理解能力角色绑定',
    '任务通过能力角色调用后端，例如「检测目标」可以绑定到某个视觉实例',
    '展开「高级：完整角色绑定与参数」，观察能力与后端的对应关系',
    '知道只有输入输出契约兼容的能力才可以互换后端',
    '空白系统还没有角色时，等以后接入自己的能力再配置'),
  step('save-config', 'system', 'system-save-config', '保存配置', '保存并检查配置',
    '保存草稿会运行静态校验，提前发现缺少的依赖和错误的绑定',
    '在「机器人参数与能力绑定」底部找到「保存并检查配置」',
    '校验结果会显示在页面，只有通过校验的草稿才能应用',
    '本课程不要求空白系统通过完整校验，也不会帮你制造虚假的就绪状态'),
  step('apply-config', 'system', 'system-config-apply-help', '保存配置', '什么时候应用配置',
    '只有将通过校验的草稿应用到停止状态的系统，新配置才会生效',
    '确认系统处于停止状态，保存并检查通过后点击出现的「应用到系统」',
    '应用成功后，新配置成为系统当前配置',
    '若还没有后端实现或校验没有通过，可先结束教学，之后再回来应用'),
  step('generic-finish', 'system', 'nav-editor', '下一步', '后端接入后再编排任务',
    '任务编排负责定义执行顺序，运行调试负责检查和实际调度',
    '记住左侧「任务编排」和「运行调试」两个入口，等系统配置完成后再使用',
    '你已经了解空白系统从草稿到应用的基本过程',
    '空白系统没有自动生成采摘任务，这是通用系统应有的默认状态'),
]

const tomatoSteps: GuideStep[] = [
  step('example-overview', 'overview', 'guide-selected-robot', '认识示例', '确认当前机器人系统',
    '总览显示当前选中的机器人系统，任务与运行状态都与这个系统关联',
    '找到当前系统名称，确认它是刚创建的番茄采摘练习系统',
    '之后看到的四后端和采摘任务都属于当前系统',
    '新建示例不会自动运行电机或机械臂'),
  step('example-system-nav', 'overview', 'nav-system', '认识示例', '进入系统搭建',
    '先认识采摘系统有哪些执行后端，再学习任务怎样调用它们',
    '点击左侧「系统搭建」',
    '进入当前番茄示例的系统搭建页面', undefined, 'nav:system'),
  step('example-vision', 'system', 'system-group-vision', '四类后端', '视觉系统做什么',
    '视觉负责检测候选番茄并提供目标信息，供后续任务节点读取',
    '查看视觉系统卡片上的绑定能力和后端名称',
    '能找到视觉能力属于哪个后端实例',
    '此处的检测结果来自模拟状态，而不是实际摄像头'),
  step('example-navigation', 'system', 'system-group-navigation', '四类后端', '导航系统做什么',
    '导航负责到达采摘作业位置，行为树可以根据导航结果决定是否继续',
    '查看导航系统的能力数量、绑定实例和状态',
    '能分清导航动作与机械臂动作是两个独立能力',
    '模拟后端不会驱动真实底盘'),
  step('example-arm', 'system', 'system-group-arm', '四类后端', '机械臂系统做什么',
    '机械臂负责计算和执行末端运动，并将成功或失败反馈给任务',
    '查看机械臂卡片的能力列表',
    '理解后面行为树中的运动节点需要对应的机械臂能力',
    '模拟成功不代表已验证运动碰撞或真实关节限位'),
  step('example-control', 'system', 'system-group-control', '四类后端', '电控与末端做什么',
    '末端电控负责夹持、释放和其他工具控制，也向任务返回操作结果',
    '查看电控与末端卡片',
    '知道执行器与电控分别承担运动和工具操作',
    '四个模拟后端共享模拟世界状态，避免互相返回矛盾结果'),
  step('example-backend-check', 'system', 'system-groups', '四类后端', '检查四后端是否已绑定',
    '卡片中的绑定能力数量表示配置关系，就绪状态表示当前运行条件',
    '重新看一遍四张卡片，区分「已绑定」和「已就绪」',
    '知道配置存在不等于后端正在运行',
    '初始状态显示未运行是正常现象'),
  step('example-editor-nav', 'system', 'nav-editor', '采摘任务', '进入任务编排',
    '任务编排用于安排视觉检测、移动、采摘和放置等动作的先后顺序',
    '点击左侧「任务编排」',
    '看到「任务模板」和「行为树编辑」两个选项', undefined, 'nav:editor'),
  step('example-tabs', 'editor', 'task-tab-template', '采摘任务', '区分模板与行为树',
    '任务模板提供参数和任务方案，行为树编辑提供节点结构和数据流',
    '先停留在「任务模板」页面，不需要直接修改 XML',
    '看到采摘任务模板及其参数与标定资产',
    '先保存模板方案，再了解行为树结构会更容易理解'),
  step('example-params', 'editor', 'task-template-parameters', '采摘任务', '理解采摘参数',
    '任务参数决定一次采摘的行为范围与限制，不同参数有不同单位和约束',
    '查看模板参数区域，先使用示例默认值，不需要随意增大动作范围',
    '能找到目标数量和恢复次数等模板限制，以及可编辑参数',
    '模板标注为只读的约束不能直接在这里修改'),
  step('example-assets', 'editor', 'task-template-asset', '采摘任务', '认识标定资产',
    '标定资产保存坐标变换或设备关联信息，错误的标定会影响真实系统定位',
    '查看「绑定标定资产」下拉框，模拟教学保持默认选项即可',
    '理解模拟资产和真实相机标定文件不能直接混用',
    '本教学不要求上传真实标定结果'),
  step('example-save-plan', 'editor', 'task-template-save', '采摘任务', '保存一份任务方案',
    '任务方案是这次运行要使用的参数快照，不等于马上开始采摘',
    '点击「保存为新任务方案」，等待界面返回并刷新任务方案列表',
    '任务方案下拉框中新增一条可选择的记录',
    '建议先保留示例参数，不执行真机操作', 'task:plan-saved'),
  step('example-preflight', 'editor', 'task-template-preflight', '采摘任务', '理解任务预检',
    '预检用于核对配置、任务参数、执行器与运行条件',
    '可以点击「预检方案」，查看是否存在未满足的条件',
    '知道预检失败会展示原因，而不是自动开始执行',
    '若 C++ 行为树执行器不可用，预检失败是正常诊断，不必强行跳过安全检查'),
  step('example-tree-tab', 'editor', 'task-tab-tree', '行为树入门', '进入行为树编辑',
    '行为树把一个大任务拆成顺序、选择和动作节点',
    '点击上方「行为树编辑」选项卡',
    '页面出现新建或加载行为树的操作入口', undefined, 'task:tree-selected'),
  step('example-tree-copy', 'editor', 'task-tree-create-example', '行为树入门', '复制示例行为树',
    '复制后的草稿可以探索节点结构，不会直接修改正在运行的任务',
    '点击「从当前系统示例创建」并等待草稿创建成功',
    '出现节点库、任务流程画布和节点设置',
    '如果提示执行器或节点模型不可用，请保留诊断信息并检查安装状态', 'task:example-created'),
  step('example-nodes', 'editor', 'task-tree-workspace', '行为树入门', '认识节点库',
    '节点库中的动作节点对应已注册能力，流程控制节点决定它们怎样组合',
    '查看视觉、导航、机械臂、电控以及流程控制分类，先不要添加新节点',
    '能区分一个动作节点和一个控制节点',
    '添加节点会改变草稿，初次学习建议先观察现有树'),
  step('example-canvas', 'editor', 'task-tree-canvas', '行为树入门', '读懂任务流程画布',
    '画布展示父子关系和任务执行结构，节点状态由运行时结果决定',
    '从树根开始，观察视觉检测、目标处理和机械臂动作所在的分支',
    '能在画布中找到节点之间的控制关系',
    '拖动画布中的节点只改变显示位置，执行顺序通过上移和下移修改'),
  step('example-node-options', 'editor', 'task-tree-node-settings', '行为树入门', '检查节点输入输出',
    '任务通过端口传递目标位姿、执行结果等信息，端口要满足类型和坐标系约束',
    '点击画布中的一个节点，再查看「节点设置」中的能力绑定与输入输出端口',
    '能看见这个节点需要哪些输入以及产生哪些输出',
    '初次教学不要求改动变量名或端口类型'),
  step('example-tree-validate', 'editor', 'task-tree-controls', '行为树入门', '理解保存和校验',
    '「保存草稿」保存编辑内容，「校验树」检查结构和端口，「发布定义」生成运行版本',
    '找到编辑器顶部的三个按钮，保留示例不变即可',
    '知道草稿、校验结果和已发布定义不是一回事',
    '发布需要满足执行器与系统快照等条件，本步不要求发布'),
  step('example-runtime-nav', 'editor', 'nav-runtime', '运行调试', '进入运行调试',
    '运行页面负责启动模块、查看就绪条件、选择任务方案和观察执行结果',
    '点击左侧「运行调试」',
    '页面显示系统启动停止按钮和就绪检查', undefined, 'nav:runtime'),
  step('example-runtime-controls', 'runtime', 'runtime-controls', '运行调试', '了解启动与停止',
    '启动系统和开始任务是两个不同的操作，停止系统用于结束模块运行',
    '找到「启动系统」和「停止系统」按钮，先不要执行任务',
    '知道只有系统处于允许启动的状态才能开始任务',
    '教学不会替你启动模块，真机操作必须由操作者确认'),
  step('example-runtime-ready', 'runtime', 'runtime-readiness', '运行调试', '怎么看就绪状态',
    '就绪检查逐项显示进程、接口、数据和授权条件',
    '查看「就绪检查」表格，找到不可用项及提示原因',
    '能判断是后端尚未启动、数据未就绪还是执行器不可用',
    'Mock 验证成功不等于 Gazebo 或 Isaac Sim 物理仿真成功'),
  step('example-runtime-plan', 'runtime', 'runtime-task-plan', '运行调试', '选择并检查任务方案',
    '只有已保存的方案才能被选中，任务预检通过后才有可能执行',
    '在「已保存方案」选择刚才创建的方案，查看「检查方案」和「开始任务」',
    '能理解「开始任务」灰色时要先排查哪些条件',
    '不要绕过任务预检，更不要用编辑器草稿代替已发布的执行定义'),
  step('example-runtime-observe', 'runtime', 'runtime-task-observation', '运行调试', '观察任务与停止结果',
    '任务运行后可以检查树结果、节点反馈、目标结果和停止确认',
    '查看「任务观察」区域，了解任务列表、取消任务和停止系统的位置',
    '知道如何查找故障原因以及如何确认停止完成',
    '没有启动过任务时，这里为空是正常的，课程到此结束'),
]

export function courseSteps(session: GuideSession): GuideStep[] {
  return [...(session.fromCreation ? [] : projectStart(session.course)), ...(session.course === 'basic' ? basicSteps : tomatoSteps)]
}
export const courseTitle = (course: CourseId) => course === 'basic' ? '通用机器人系统教学' : '番茄采摘示例教学'

/** 页面只在真正完成操作后发送事件，不能在点击前发送 */
export function guideCompleted(event: string) {
  window.dispatchEvent(new CustomEvent<string>('agro:guide-complete', { detail: event }))
}
