import HsmRuntime from '../HsmRuntime'
import RuntimeTree from '../TaskEditor/RuntimeTree'
import {guideCompleted} from '../../guide/courses'
import { useEffect,useRef,useState } from 'react'
import { Panel,Field,StatusCard } from '../../components/Foundation'
import { ApiError } from '../../api'
import { ErrorFields,finishIntent,durableIntent,requestId,useOperation,waitJob,type Json,type PageProps } from '../shared'
import type {Workspace} from '../../types'

export default function RuntimePage({client,observation,language,changed,onNavigate}:PageProps & {onNavigate:(page:Workspace)=>void}){
 const [preflight,setPreflight]=useState<Json|null>(null),[plans,setPlans]=useState<Json[]>([]),[definitions,setDefinitions]=useState<Json[]>([]),[planId,setPlanId]=useState(''),[diagnostics,setDiagnostics]=useState<Json|null>(null),[tasks,setTasks]=useState<Json[]>([]),[selected,setSelected]=useState(()=>localStorage.getItem('agro.last_task')||''),[task,setTask]=useState<Json|null>(null),[stale,setStale]=useState(false)
 const intent=useRef<string|null>(localStorage.getItem('agro.task_request'))
 const op=useOperation(language)
 useEffect(()=>{let active=true;const controller=new AbortController();async function load(){try{const [p,d,t,defs]=await Promise.all([client.request<Json>('/plans','GET',undefined,controller.signal),client.request<Json>('/diagnostics','GET',undefined,controller.signal),client.request<Json>('/tasks','GET',undefined,controller.signal),client.request<Json>('/trees/definitions','GET',undefined,controller.signal)]);if(!active)return;setPlans(p.plans);setDefinitions(defs.definitions);setDiagnostics(d);setTasks(t.tasks);if(selected){const detail=await client.request<Json>(`/tasks/${encodeURIComponent(selected)}`,'GET',undefined,controller.signal);if(active)setTask(detail)}else if(intent.current){const found=await client.request<Json>(`/tasks/by-request/${intent.current}`,'GET',undefined,controller.signal);if(active&&found.found)remember(found.task)}if(active)setStale(false)}catch(e){if(active){setStale(true);op.setError(e)}}}void load();return()=>{active=false;controller.abort()}},[client,observation,selected])
 function remember(next:Json){setSelected(next.task_run_id);setTask(next);localStorage.setItem('agro.last_task',next.task_run_id)}
 async function lifecycle(action:'start'|'stop',phase:(v:string)=>void,signal?:AbortSignal){const id=durableIntent(action,{snapshot:observation?.system.snapshot_id,run:observation?.system.system_run_id});const accepted=await client.request<Json>(`/system/${action}`,'POST',{request_id:id});try{await waitJob(client,accepted.management_job_id,phase,signal);finishIntent(action);guideCompleted(action==='start'?'system:started':'system:stopped')}catch(e){if(e instanceof ApiError&&e.details?.some(x=>['failed','rolled_back','blocked'].includes(x.code)))finishIntent(action);throw e}await changed()}
 async function startTask(phase:(v:string)=>void){
  const [kind,id]=planId.split(':',2)
  const key=durableIntent('task',{kind,id,previous:task&& !['RUNNING','ACCEPTED','CANCELING'].includes(task.state)?task.task_run_id:null})
  intent.current=key;localStorage.setItem('agro.task_request',key)
  try{remember(await client.request<Json>(kind==='tree'?`/trees/definitions/${id}/start`:`/plans/${id}/start`,'POST',{request_id:key}))}
  catch(e){if(e instanceof ApiError&&e.kind==='offline'){phase('核对原任务请求');const found=await client.request<Json>(`/tasks/by-request/${key}`);if(found.found)remember(found.task);else throw e}else throw e}
  await changed()
 }
 async function cancel(phase:(v:string)=>void,signal:AbortSignal){if(!selected)return;remember(await client.request<Json>(`/tasks/${selected}/cancel`,'POST',{}));const deadline=Date.now()+15000;while(Date.now()<deadline){signal.throwIfAborted();const next=await client.request<Json>(`/tasks/${selected}`,'GET',undefined,signal);remember(next);phase(`取消 · ${next.state} · 停止${next.stop_confirmed?'已确认':'未确认'}`);if(!['ACCEPTED','RUNNING','CANCELING'].includes(next.state)){if(!next.stop_confirmed)throw new ApiError('response',[{path:'$.stop_confirmed',code:'stop_unconfirmed',reason:'任务结束但设备停止未确认，保留停止处理入口'}]);return}await new Promise(r=>setTimeout(r,400))}throw new ApiError('response',[{path:'$.stop_confirmed',code:'observation_timeout',reason:'取消结果尚未确认，请继续核对该任务'}])}
 const active=task&&['ACCEPTED','RUNNING','CANCELING'].includes(task.state)
 const capabilities:Json[]=diagnostics?.capabilities||[]
 const problems=capabilities.flatMap(cap=>(['process','interface','data','authorization'] as const).filter(k=>!cap.checks?.[k]?.ready).map(k=>({instance:cap.backend_instance,capability:cap.capability_id,kind:k,reason:cap.checks[k]?.reason?.reason||'尚未满足运行条件'})))
 const blockers=[
  ...(!diagnostics?.executor_available?['行为树执行器不可用']:[]),
  ...(observation?.system.state==='STOPPED'?['系统未启动']:[]),
  ...(observation?.system.state==='FAULT'?['系统故障 · 需检查设备状态']:[]),
  ...(!planId?['尚未选择任务']:[]),
  ...(stale?['运行核心连接中断']:[]),
 ]
 const checkTitle:Record<string,string>={process:'启动进程',interface:'连接接口',data:'检查数据',authorization:'检查授权'}
 const nextAction=(kind:string)=>kind==='authorization'?'检查控制权限':kind==='data'?'检查数据更新时间':kind==='interface'?'检查接口连接': '检查后端进程'
 
 const stop=()=>void op.run('停止系统',(phase,signal)=>lifecycle('stop',phase,signal))
 const cancelNow=()=>void op.run('取消任务',cancel)
 return <><div className="runtime-dashboard"><div><span className="eyebrow">RUN CONTROL</span><h2>运行与调试</h2><p>系统控制、任务执行与状态诊断</p></div><div><span className="runtime-state">{observation?.system.state||'状态未知'}</span><button onClick={()=>onNavigate('editor')}>返回任务编辑 →</button></div></div><div data-guide="runtime-controls" className="buttons"><button data-guide="runtime-start" className="primary" disabled={op.busy||stale||observation?.system.state!=='STOPPED'} onClick={()=>void op.run('启动系统',(phase,signal)=>lifecycle('start',phase,signal))}>启动系统</button><button data-guide="runtime-stop" disabled={op.busy} onClick={stop}>停止系统</button><button disabled={op.busy||observation?.system.state!=='READY'} onClick={()=>void op.run('显式接管手动控制',async()=>{await client.request('/control/take','POST',{mode:'MANUAL',lease_s:30});await changed()})}>接管手动控制（高级）</button></div>
 <p className="callout">任务启动需要满足系统就绪和控制权限条件</p>
 {stale&&<p role="status" className="error">连接中断，正在等待任务状态更新</p>}
 <div className="studio-runtime-guide"><h3>运行前确认</h3><p>运行条件与待处理问题</p>{blockers.length||problems.length?<div className="studio-runtime-problems">{blockers.map((b,i)=><div key={i}><span>!</span><strong>{b}</strong>{b.includes('任务')?<button onClick={()=>onNavigate('editor')}>打开任务 →</button>:b.includes('系统')?<button onClick={()=>onNavigate('system')}>查看系统 →</button>:null}</div>)}{problems.slice(0,8).map((b,i)=><div key={i}><span>!</span><strong>{b.instance} · {checkTitle[b.kind]}：{b.reason}</strong><small>{nextAction(b.kind)}</small><button onClick={()=>onNavigate('system')}>查看后端 →</button></div>)}</div>:<div className="studio-runtime-ready">已收到运行条件信息，仍需在启动任务前确认设备环境安全</div>}</div>
 <div data-guide="runtime-readiness"><Panel title="能力就绪详情" icon="system"><div className="readiness-heading"><p>执行器 {diagnostics?.executor_available?'已配置':'不可用'} · 模块日志尚不可用</p><button onClick={()=>onNavigate('system')}>检查系统接入 →</button></div>{!diagnostics?.executor_available&&<p className="callout">行为树执行器未安装或不可用 · 请检查 task_engine 构建状态</p>}<details className="studio-advanced"><summary>展开详细能力状态</summary><div className="table-wrap"><table><thead><tr><th>能力</th><th>进程</th><th>接口</th><th>数据</th><th>授权</th></tr></thead><tbody>{diagnostics?.capabilities.map((c:Json)=><tr key={c.backend_instance+c.capability_id}><td>{c.backend_instance} · {c.capability_id}</td>{['process','interface','data','authorization'].map(k=><td key={k} className={c.checks[k].ready?'readiness-ok':'readiness-issue'}>{c.checks[k].ready?'✓ 就绪':c.checks[k].reason?.reason||'待检查'}</td>)}</tr>)}</tbody></table></div></details></Panel></div>
 <HsmRuntime client={client} observation={observation} language={language} changed={changed} onNavigate={onNavigate}/><div data-guide="runtime-task-plan"><Panel title="运行机器人任务" icon="templates"><Field label="选择已发布任务或示例方案"><select value={planId} onChange={e=>{setPlanId(e.target.value);setPreflight(null)}}><option value="">选择任务</option>{definitions.map(d=><option key={d.id} value={'tree:'+d.id}>{d.layout?.labels?.[d.document.trees?.[d.document.main_tree_id]?.root_id]||d.document.main_tree_id}</option>)}{plans.map(p=><option key={p.id} value={'plan:'+p.id}>示例方案 · {p.id.slice(-8)}</option>)}</select></Field><div className="buttons"><button disabled={op.busy||!planId} onClick={()=>void op.run('任务检查',async()=>{const [kind,id]=planId.split(':',2);const result=await client.request<Json>(kind==='tree'?`/trees/definitions/${id}/preflight`:`/plans/${id}/preflight`);setPreflight(result);if(!result.valid)throw new ApiError('response',result.errors)})}>检查任务</button><button className="primary" disabled={op.busy||stale||!planId||observation?.system.state!=='READY'||!!active||observation?.control.mode!=='STANDBY'} onClick={()=>void op.run('开始任务并核对原请求',startTask)}>开始任务</button></div><details><summary>高级：查看上次运行请求标识</summary><code>{intent.current||'暂无'}</code></details>{preflight&&<p className={preflight.valid?'studio-runtime-ready':'studio-warning'}>{preflight.valid?'预检通过 · 请确认工作区域安全':'预检未通过 · 查看诊断详情'}</p>}</Panel></div>
 <div data-guide="runtime-task-observation"><Panel title="任务观察" icon="runtime"><Field label="已有任务"><select value={selected} onChange={e=>{setSelected(e.target.value);setTask(null);localStorage.setItem('agro.last_task',e.target.value)}}><option value="">未选择</option>{tasks.map(t=><option key={t.task_run_id} value={t.task_run_id}>{t.task_run_id} · {t.state}</option>)}</select></Field>
 {task&&<><details><summary>查看执行 ID</summary><p><code>{task.task_run_id}</code></p></details><div className="cards"><StatusCard label="任务状态" value={task.state}/><StatusCard label="树结果" value={task.tree_state}/><StatusCard label="设备停止" value={task.stop_confirmed?'已确认':'未确认'} tone={task.stop_confirmed?'neutral':'danger'}/></div><div className="buttons"><button disabled={op.busy||!active} onClick={cancelNow}>取消任务</button><button data-guide="runtime-stop" disabled={op.busy} onClick={stop}>停止系统</button></div><ErrorFields value={task.error?{errors:[task.error]}:null}/><details><summary>目标结果与节点反馈（高级）</summary><h3>目标结果</h3><pre>{JSON.stringify(task.targets,null,2)}</pre><h3>节点与操作反馈</h3><pre>{JSON.stringify({nodes:task.nodes,operations:task.operations},null,2)}</pre></details>{task.state==='UNKNOWN'&&<p className="error">任务结果未知，请检查日志及设备状态</p>}</>}
 </Panel></div>{task&&<RuntimeTree task={task} language={language}/>}<ErrorFields value={op.error}/>{op.dialog(<><button disabled={!selected||!active} onClick={()=>{void client.request(`/tasks/${selected}/cancel`,'POST',{}).then(()=>changed()).catch(op.setError)}}>取消当前任务</button><button onClick={()=>{void client.request<Json>('/system/stop','POST',{request_id:requestId()}).then(()=>changed()).catch(op.setError)}}>请求停止系统</button></>)}</>
}
