import { useEffect,useRef,useState } from 'react'
import { Panel,Field,StatusCard } from '../../components/Foundation'
import { ApiError } from '../../api'
import { ErrorFields,finishIntent,durableIntent,requestId,useOperation,waitJob,type Json,type PageProps } from '../shared'

export default function RuntimePage({client,observation,language,changed}:PageProps){
 const [plans,setPlans]=useState<Json[]>([]),[planId,setPlanId]=useState(''),[diagnostics,setDiagnostics]=useState<Json|null>(null),[tasks,setTasks]=useState<Json[]>([]),[selected,setSelected]=useState(()=>localStorage.getItem('agro.last_task')||''),[task,setTask]=useState<Json|null>(null),[stale,setStale]=useState(false)
 const intent=useRef<string|null>(localStorage.getItem('agro.task_request'))
 const op=useOperation(language)
 useEffect(()=>{let active=true;const controller=new AbortController();async function load(){try{const [p,d,t]=await Promise.all([client.request<Json>('/plans','GET',undefined,controller.signal),client.request<Json>('/diagnostics','GET',undefined,controller.signal),client.request<Json>('/tasks','GET',undefined,controller.signal)]);if(!active)return;setPlans(p.plans);setDiagnostics(d);setTasks(t.tasks);if(selected){const detail=await client.request<Json>(`/tasks/${encodeURIComponent(selected)}`,'GET',undefined,controller.signal);if(active)setTask(detail)}else if(intent.current){const found=await client.request<Json>(`/tasks/by-request/${intent.current}`,'GET',undefined,controller.signal);if(active&&found.found)remember(found.task)}if(active)setStale(false)}catch(e){if(active){setStale(true);op.setError(e)}}}void load();return()=>{active=false;controller.abort()}},[client,observation,selected])
 function remember(next:Json){setSelected(next.task_run_id);setTask(next);localStorage.setItem('agro.last_task',next.task_run_id)}
 async function lifecycle(action:'start'|'stop',phase:(v:string)=>void,signal?:AbortSignal){const id=durableIntent(action,{snapshot:observation?.system.snapshot_id,run:observation?.system.system_run_id});const accepted=await client.request<Json>(`/system/${action}`,'POST',{request_id:id});try{await waitJob(client,accepted.management_job_id,phase,signal);finishIntent(action)}catch(e){if(e instanceof ApiError&&e.details?.some(x=>['failed','rolled_back','blocked'].includes(x.code)))finishIntent(action);throw e}await changed()}
 async function startTask(phase:(v:string)=>void){
  const key=durableIntent('task',{plan_id:planId,previous:task&& !['RUNNING','ACCEPTED','CANCELING'].includes(task.state)?task.task_run_id:null})
  intent.current=key;localStorage.setItem('agro.task_request',key)
  try{remember(await client.request<Json>(`/plans/${planId}/start`,'POST',{request_id:key}))}
  catch(e){if(e instanceof ApiError&&e.kind==='offline'){phase('核对原任务请求');const found=await client.request<Json>(`/tasks/by-request/${key}`);if(found.found)remember(found.task);else throw e}else throw e}
  await changed()
 }
 async function cancel(phase:(v:string)=>void,signal:AbortSignal){if(!selected)return;remember(await client.request<Json>(`/tasks/${selected}/cancel`,'POST',{}));const deadline=Date.now()+15000;while(Date.now()<deadline){signal.throwIfAborted();const next=await client.request<Json>(`/tasks/${selected}`,'GET',undefined,signal);remember(next);phase(`取消 · ${next.state} · 停止${next.stop_confirmed?'已确认':'未确认'}`);if(!['ACCEPTED','RUNNING','CANCELING'].includes(next.state)){if(!next.stop_confirmed)throw new ApiError('response',[{path:'$.stop_confirmed',code:'stop_unconfirmed',reason:'任务结束但设备停止未确认，保留停止处理入口'}]);return}await new Promise(r=>setTimeout(r,400))}throw new ApiError('response',[{path:'$.stop_confirmed',code:'observation_timeout',reason:'取消结果尚未确认，请继续核对该任务'}])}
 const active=task&&['ACCEPTED','RUNNING','CANCELING'].includes(task.state)
 const stop=()=>void op.run('停止系统',(phase,signal)=>lifecycle('stop',phase,signal))
 const cancelNow=()=>void op.run('取消任务',cancel)
 return <><div className="buttons"><button disabled={op.busy||stale||observation?.system.state!=='STOPPED'} onClick={()=>void op.run('启动系统',(phase,signal)=>lifecycle('start',phase,signal))}>启动系统</button><button disabled={op.busy} onClick={stop}>停止系统</button><button disabled={op.busy||observation?.system.state!=='READY'} onClick={()=>void op.run('显式接管手动控制',async()=>{await client.request('/control/take','POST',{mode:'MANUAL',lease_s:30});await changed()})}>接管手动控制</button></div>
 <p className="callout">先检查配置与资产，再启动系统并开始任务，检查不会获取 AUTO 权限，接管为显式操作</p>
 {stale&&<p role="status" className="error">数据陈旧 · 保留原任务 ID，网络恢复后继续查询，不重新派发</p>}
 <Panel title="就绪检查" icon="system"><p>执行器 {diagnostics?.executor_available?'已配置':'不可用'} · 模块日志尚不可用</p><div className="table-wrap"><table><thead><tr><th>能力</th><th>进程</th><th>接口</th><th>数据</th><th>授权</th></tr></thead><tbody>{diagnostics?.capabilities.map((c:Json)=><tr key={c.backend_instance+c.capability_id}><td>{c.backend_instance} · {c.capability_id}</td>{['process','interface','data','authorization'].map(k=><td key={k}>{c.checks[k].ready?'就绪':c.checks[k].reason?.reason||'未就绪'}</td>)}</tr>)}</tbody></table></div></Panel>
 <Panel title="开始模板任务" icon="templates"><Field label="已保存方案"><select value={planId} onChange={e=>setPlanId(e.target.value)}><option value="">选择任务方案</option>{plans.map(p=><option key={p.id} value={p.id}>{p.id} · approach_dz {p.parameters.approach_dz}</option>)}</select></Field><div className="buttons"><button disabled={op.busy||!planId} onClick={()=>void op.run('任务预检',async()=>{const result=await client.request<Json>(`/plans/${planId}/preflight`);if(!result.valid)throw new ApiError('response',result.errors)})}>检查方案</button><button className="primary" disabled={op.busy||stale||!planId||observation?.system.state!=='READY'||!!active||observation?.control.mode!=='STANDBY'} onClick={()=>void op.run('开始任务并核对原请求',startTask)}>开始任务</button></div><p className="muted">请求标识 {intent.current||'尚未请求'} · 超时后沿用相同请求核对</p></Panel>
 <Panel title="任务观察" icon="runtime"><Field label="已有任务"><select value={selected} onChange={e=>{setSelected(e.target.value);setTask(null);localStorage.setItem('agro.last_task',e.target.value)}}><option value="">未选择</option>{tasks.map(t=><option key={t.task_run_id} value={t.task_run_id}>{t.task_run_id} · {t.state}</option>)}</select></Field>
 {task&&<><p><code>{task.task_run_id}</code></p><div className="cards"><StatusCard label="任务状态" value={task.state}/><StatusCard label="树结果" value={task.tree_state}/><StatusCard label="设备停止" value={task.stop_confirmed?'已确认':'未确认'} tone={task.stop_confirmed?'neutral':'danger'}/></div><div className="buttons"><button disabled={op.busy||!active} onClick={cancelNow}>取消任务</button><button disabled={op.busy} onClick={stop}>停止系统</button></div><ErrorFields value={task.error?{errors:[task.error]}:null}/><h3>目标结果</h3><pre>{JSON.stringify(task.targets,null,2)}</pre><h3>节点与操作反馈</h3><pre>{JSON.stringify({nodes:task.nodes,operations:task.operations},null,2)}</pre>{task.state==='UNKNOWN'&&<p className="error">结果未知，只能核对原因，当前界面不提供解除或重试</p>}</>}
 </Panel><ErrorFields value={op.error}/>{op.dialog(<><button disabled={!selected||!active} onClick={()=>{void client.request(`/tasks/${selected}/cancel`,'POST',{}).then(()=>changed()).catch(op.setError)}}>取消当前任务</button><button onClick={()=>{void client.request<Json>('/system/stop','POST',{request_id:requestId()}).then(()=>changed()).catch(op.setError)}}>请求停止系统</button></>)}</>
}
